version: '3.1'

services:
  db:
    image: mysql:8.0
    container_name: todo-mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3306:3306
